[package]
name = "salvo"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = """
Salvo is a powerful and simplest web server framework in Rust world.
"""
homepage.workspace = true
repository.workspace = true
documentation.workspace = true
readme.workspace = true
keywords.workspace = true
license.workspace = true
categories.workspace = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[badges]
codecov = { repository = "salvo-rs/salvo", branch = "main", service = "github" }

[lib]
name = "salvo"
path = "src/lib.rs"

[features]
default = ["test", "cookie"]
full = [
    "test",
    "cookie",
    "rustls",
    "native-tls",
    "openssl",
    "unix",
    "acme",
    "anyhow",
    "extra",
]
cookie = ["salvo_core/cookie"]
rustls = ["salvo_core/rustls"]
native-tls = ["salvo_core/native-tls"]
openssl = ["salvo_core/openssl"]
unix = ["salvo_core/unix"]
acme = ["salvo_core/acme"]
anyhow = ["salvo_core/anyhow"]
test = ["salvo_core/test"]
affix = ["salvo_extra/affix"]
extra = ["salvo_extra/full"]
basic-auth = ["salvo_extra/basic-auth"]
force-https = ["salvo_extra/force-https"]
jwt-auth = ["salvo_extra/jwt-auth"]
compression = ["salvo_extra/compression"]
logging = ["salvo_extra/logging"]
proxy = ["salvo_extra/proxy"]
serve-static = ["salvo_extra/serve-static"]
size-limiter = ["salvo_extra/size-limiter"]
sse = ["salvo_extra/sse"]
trailing-slash = ["salvo_extra/trailing-slash"]
timeout = ["salvo_extra/timeout"]
ws = ["salvo_extra/ws"]
caching-headers = ["salvo_extra/caching-headers"]

[dependencies]
salvo_core = { workspace = true, default-features = false, path = "../core" }
salvo_extra = { workspace = true, default-features = false, optional = true, path = "../extra" }
