[package]
name = "example-catch-panic"
version.workspace = true
edition.workspace = true
publish.workspace = true


[dependencies]
anyhow = "1"
salvo = { workspace = true, features=["catch-panic"] }
tokio = { version = "1", features = ["macros"] }
tracing = "0.1"
tracing-subscriber = "0.3"
