[package]
name = "salvo-session"
version.workspace = true
authors.workspace = true
edition.workspace = true
description = """
Session support for salvo web server framework.
"""
homepage.workspace = true
repository.workspace = true
readme = "../README.md"
keywords = ["http", "session", "web", "framework", "server"]
license.workspace = true
categories.workspace = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
async-session = { version = "3"}
cookie = { version = "0.16", features = ["percent-encode", "signed"] }
salvo_core = { version = "0.35.2", default-features = false, path = "../core" }
tracing = { version = "0.1" }

[dev-dependencies]
salvo_core = { features = ["test"], path = "../core" }
tracing-test.workspace = true
reqwest.workspace = true
