[profile.dev]
codegen-units = 4

[badges]
codecov = { repository = "kenorld/salvo", branch = "master", service = "github" }

[workspace]
members = [
  "salvo",
  "core",
  "extra",
  "macro",
  "examples/hello_world",
  "examples/file_list",
  "examples/basic_auth",
]

[patch.crates-io]
salvo = { path = "salvo" }
salvo_core = { path = "core" }
salvo_macro = { path = "macro" }
salvo_extra = { path = "extra" }
