[profile.dev]
codegen-units = 4

[workspace]
members = [ "core",
  "examples/basic_auth", "examples/file_list",
  "examples/hello_world",
  "extra",
  "macro",
  "salvo",
]

[patch.crates-io]
salvo = { path = "salvo" }
salvo_core = { path = "core" }
salvo_macro = { path = "macro" }
salvo_extra = { path = "extra" }
