[workspace]
members = ["crates/*", "examples/*"]

[workspace.package]
version = "0.35.2"
authors = ["Chrislearn Young <chrislearn@hotmail.com>"]
edition = "2021"
description = """
Salvo is a powerful and simplest web server framework in Rust world.
"""
homepage = "https://salvo.rs"
repository = "https://github.com/salvo-rs/salvo"
documentation = "https://docs.rs/salvo/"
readme = "./README.md"
keywords = ["http", "async", "web", "framework", "server"]
license = "MIT OR Apache-2.0"
categories = ["web-programming::http-server", "web-programming::websocket", "network-programming", "asynchronous"]

[workspace.dependencies]
anyhow = "1"
async-session = "3"
async-trait = "0.1"
base64 = "0.13"
bytes = "1"
chrono = "0.4"
cookie = "0.16"
cruet = "0.13"
encoding_rs = "0.8"
enumflags2 = "0.7"
fastrand = "1.5"
form_urlencoded = "1"
futures-util = "0.3"
headers = "0.3"
http = "0.2"
hyper = "0.14"
hyper-rustls = "0.23"
mime = "0.3"
mime_guess = "2"
multimap = "0.8"
once_cell = "1"
path-slash = "0.2"
parking_lot = "0.12"
percent-encoding = "2"
pin-project = "1"
rand = "0.8"
regex = "1"
reqwest = "0.11"
rust-embed = "6"
salvo_macros = { version = "0.35.2", path = "./crates/macros" }
salvo_core = { version = "0.35.2", path = "./crates/core" }
salvo_extra = { version = "0.35.2", path = "./crates/extra" }
salvo-session = { version = "0.35.2", path = "./crates/session" }
serde = "1"
serde_json = "1"
serde_urlencoded = "0.7"
syn = "1"
thiserror = "1"
tokio = "1"
tokio-stream = "0.1"
tokio-util = "0.7"
tracing = "0.1"
tracing-test = "0.2.1"
url = "2"
darling = "0.14"
proc-macro-crate = "1"
proc-macro2 = "1"
quote = "1"
