[profile.dev]
codegen-units = 4

[workspace]
members = [
  "salvo",
  "core",
  "extra",
  "macros",
  "examples/hello_world",
  "examples/file_list",
  "examples/basic_auth",
]

[patch.crates-io]
salvo_core = { path = "core" }
salvo_macros = { path = "macros" }
salvo_extra = { path = "extra" }
