[profile.dev]
codegen-units = 4

[workspace]
members = [
  "core",
  "extra",
  "macros",
  "examples/hello_world",
  "examples/file_list",
  "examples/basic_auth",
]

[patch.crates-io]
novel = { path = "core" }
# novel_macros = { path = "macros" }
novel_extra = { path = "extra" }
