[package]
name = "salvo"
version = "0.16.1"
authors = ["Chrislearn Young <chrislearn@hotmail.com>"]
edition = "2021"
description = """
Salvo is a powerful and simplest web server framework in Rust world.
"""
homepage = "https://salvo.rs"
repository = "https://github.com/salvo-rs/salvo"
documentation = "https://docs.rs/salvo/"
readme = "./README.md"
keywords = ["salvo", "web", "framework", "server"]
license = "MIT OR Apache-2.0"
categories = ["network-programming", "asynchronous", "web-programming::http-server", "web-programming::websocket"]
autoexamples = true

[package.metadata.docs.rs]
all-features = true

[badges]
codecov = { repository = "salvo-rs/salvo", branch = "master", service = "github" }

[lib]
name = "salvo"
path = "src/lib.rs"

[features]
default = []
full = ["extra", "rustls", "anyhow", "native_tls"]
rustls = ["salvo_core/rustls"]
native_tls = ["salvo_core/native_tls"]
anyhow = ["salvo_core/anyhow"]
extra = ["basic_auth", "jwt_auth", "compression", "cors", "csrf", "proxy", "serve", "sse", "ws", "size_limiter"]
basic_auth = ["salvo_extra/basic_auth"]
jwt_auth = ["salvo_extra/jwt_auth"]
compression = ["salvo_extra/compression"]
cors = ["salvo_extra/cors"]
csrf = ["salvo_extra/csrf"]
proxy = ["salvo_extra/proxy"]
serve = ["salvo_extra/serve"]
sse = ["salvo_extra/sse"]
ws = ["salvo_extra/ws"]
size_limiter = ["salvo_extra/size_limiter"]

[workspace]
members = [".", "core", "extra", "macros"]

[dependencies]
salvo_core = { version = "0.16.1", default-features = false, path = "./core" }
salvo_extra = { version = "0.16.0", default-features = false, optional = true, path = "./extra" }

[dev-dependencies]
async-stream = "0.3"
futures-util = { version = "0.3", default-features = false }
once_cell = "1"
serde = "1"
serde_derive = "1"
salvo = { path = ".", features = ["full"] }
tokio = { version = "1", features = ["full"] }
tokio-stream = { version = "0.1", features = ["net"] }
tracing = "0.1"
tracing-log = "0.1"
tracing-subscriber = "0.3.0"
tower = { version = "0.4", features = ["limit"] }
hyper = { version = "0.14", features = ["server"] }

[profile.release]
codegen-units = 1
incremental = false

[profile.bench]
codegen-units = 1
incremental = false