[package]
name = "example-basic-auth"
version = "0.1.0"
edition = "2021"
publish = false


[dependencies]
salvo = { path = "../../salvo", features=["basic-auth"] }
tokio = "1"
tracing-subscriber = "0.3"
tracing = "0.1"