[package]
name = "hello_world"
version = "0.0.0"
workspace = "../../"
edition = "2018"
publish = false

[dependencies]
tracing = "0.1"
tracing-subscriber = "0.2"
tracing-futures = "0.2"
salvo = { path = "../../salvo" }
tokio = { version = "0.3.0", features = ["full"] }
