[package]
name = "hello_world"
version = "0.0.0"
workspace = "../../"
edition = "2018"
publish = false

[dependencies]
salvo = { path = "../../salvo" }
tokio = { version = "0.3.0", features = ["full"] }
