[package]
name = "example-todos"
version = "0.1.0"
edition = "2021"
publish = false


[dependencies]
once_cell = "1"
salvo = { path = "../../salvo" }
serde = { version = "1.0.118", features = ["derive"] }
tokio = "1"
tracing = "0.1"
tracing-subscriber = "0.3"

[dev-dependencies]
reqwest = { version = "0.11", features = ["json"] }
