[package]
name = "salvo_extra"
version = "0.13.2"
authors = ["Chrislearn Young <chrislearn@hotmail.com>"]
edition = "2021"
description = """
A simple web framework written by rust
"""
homepage = "https://github.com/salvo-rs/salvo"
repository = "https://github.com/salvo-rs/salvo"
readme = "../README.md"
keywords = ["salvo", "web", "framework", "server"]
license = "MIT OR Apache-2.0"
categories = ["network-programming", "asynchronous", "web-programming::http-server", "web-programming::websocket"]

[package.metadata.docs.rs]
all-features = true

[features]
default = ["full"]
full = ["basic_auth", "jwt_auth", "compression", "cors", "proxy", "serve", "sse", "ws", "size_limiter"]
basic_auth = ["base64", "thiserror"]
jwt_auth = ["cookie", "jsonwebtoken"]
compression = ["async-compression", "tokio", "tokio-stream", "tokio-util"]
cors = []
size_limiter = []
proxy = ["hyper", "hyper-rustls/webpki-tokio"]
serve = ["chrono", "mime", "percent-encoding", "tokio"]
sse = ["futures-util", "pin-project", "tokio"]
ws = ["futures-util", "tokio", "tokio-tungstenite"]

[dependencies]
async-compression = { version = "0.3", features = ["brotli", "deflate", "gzip", "tokio"], optional = true }
async-trait = { version = "0.1" }
base64 = { version = "0.13", optional = true }
chrono = { version = "0.4", features = ["serde"], optional = true }
cookie = { version = "0.15", features = ["percent-encode"], optional = true }
futures-util = { version = "0.3", default-features = false, optional = true }
hyper = { version = "0.14", features = ["stream", "server", "http1", "http2", "tcp", "client"], optional = true }
hyper-rustls = { version = "0.22.1", default-features = false, optional = true }
jsonwebtoken = { version = "7", optional = true }
mime = { version = "0.3", optional = true }
percent-encoding = { version = "2.1", optional = true }
pin-project = { version = "1.0", optional = true }
salvo_core = { version = "0.13", default-features = false, path = "../core" }
serde = { version = "1" }
serde_derive = { version = "1" }
serde_json = { version = "1" }
thiserror = { version = "1", optional = true }
tokio = { version = "1.5", features = ["fs", "sync", "time"], optional = true }
tokio-stream = { version = "0.1", optional = true }
tokio-tungstenite = { version = "0.15", default-features = false, optional = true }
tokio-util = { version = "0.6", features = ["io"], optional = true }
tracing = { version = "0.1" }

[dev-dependencies]
reqwest = "0.11"
