[package]
name = "novel_extra"
version = "0.5.0"
authors = ["Chrislearn Young <chrislearn@hotmail.com>"]
edition = "2018"
description = """
my web framework.
"""
homepage = "https://github.com/kenorld/novel"
repository = "https://github.com/kenorld/novel"
readme = "../README.md"
keywords = ["novel", "web", "framework", "server"]
license = "MIT/Apache-2.0"
categories = ["web-programming::http-server"]

[package.metadata.docs.rs]
all-features = true

[dependencies]
futures = "0.3"
async-trait = "0.1.22"
smallvec = "0.6"
http = "0.2"
yansi = "0.5"
toml = "0.4.7"
num_cpus = "1.0"
state = "0.4.1"
time = "0.1"
memchr = "2"
mime = "0.3.14"
base64 = "0.10"
isatty = "0.1"
url = "2.1.0"
cookie = { version = "0.12.0", features = ["percent-encode"] }
hyper = { version = "0.13", features = ["stream", "tcp"] }
percent-encoding = "1"
indexmap = "1.0.2"
regex = "1.1.6"
unicode-xid = "0.1"
typemap = "0.3"
lazy_static = "1.4"
config = "0.9.3"
serde = "1.0.101"
serde_derive = "1.0.101"
serde_json = "1.0.41"
serde_urlencoded = "0.5.1"
jsonwebtoken = "6"
chrono = { version = "0.4", features = ["serde"] }
novel = {version = "0.5.0", default-features = false}

[build-dependencies]
yansi = "0.5"
version_check = "0.1.3"
