base_url = "https://www.salvo.pub/"
title = "Salvo"
description = "Simple web framework written by rust"

compile_sass = true
highlight_code = true
insert_anchor_links = true
highlight_theme = "kronuz"
build_search_index = true

[extra]
author = "Chrislearn Young"
