[package]
name = "example-jwt-auth"
version.workspace = true
edition.workspace = true
publish.workspace = true


[dependencies]
anyhow = "1"
jsonwebtoken = "8.0"
salvo = { workspace = true, features = ["anyhow", "jwt-auth"] }
serde = "1"
time = "0.3"
tokio = { version = "1", features = ["macros"] }
tracing = "0.1"
tracing-subscriber = "0.3"
