[package]
name = "sea-orm-salvo-example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
members = [".", "entity", "migration"]

[dependencies]
tokio = { version = "1.21.1", features = ["macros", "rt-multi-thread"] }
salvo = { version = "0.35.1", features = ["affix", "serve-static"] }
tracing = "0.1.36"
tracing-subscriber = { version = "0.3.15", features = ["env-filter"] }
serde = { version = "1.0.144", features = ["derive"] }
tera = "1.17.1"
dotenv = "0.15"
entity = { path = "entity" }
migration = { path = "migration" }
sea-orm = { version = "0.9.2", features = [
  "debug-print",
  "runtime-tokio-native-tls",
  "sqlx-sqlite",
  # "sqlx-postgres",
  # "sqlx-mysql",
] }
