[package]
name = "example-handle-error"
version = "0.1.0"
edition = "2021"
publish = false


[dependencies]
anyhow = "1"
salvo = { path = "../../salvo", features = ["anyhow"] }
tokio = "1"
tracing = "0.1"
tracing-subscriber = "0.3"
