[package]
name = "novel"
version = "0.5.0"
authors = ["Chrislearn Young <chrislearn@hotmail.com>"]
edition = "2018"
description = """
my web framework.
"""
homepage = "https://github.com/kenorld/novel"
repository = "https://github.com/kenorld/novel"
readme = "../README.md"
keywords = ["novel", "web", "framework", "server"]
license = "MIT/Apache-2.0"
categories = ["web-programming::http-server"]

[package.metadata.docs.rs]
all-features = true

[dependencies]
futures = { version = "0.3", features = ["std"] }
futures-cpupool = "0.1"
http = "0.2"
yansi = "0.5"
toml = "0.4.7"
num_cpus = "1.0"
state = "0.4.1"
time = "0.1"
memchr = "2"
base64 = "0.10"
isatty = "0.1"
url = "2.1.0"
cookie = { version = "0.12", features = ["percent-encode"] }
hyper = { version = "0.13", features = ["stream", "tcp"] }
regex = "1.1.6"
lazy_static = "1.4"
config = "0.9.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_cbor = "0.10"
serde_urlencoded = "0.5.1"
mime = "0.3.14"
mime_guess = "2.0.1"
slog = { version = "2.5.2", features = ["max_level_trace", "release_max_level_warn"] }
slog-term = "2.4.2"
httparse = "1.2"
tempdir = "0.3"
textnonce = "0.6"
buf-read-ext = "0.3"
encoding = "0.2"
bitflags = "1.2"
bytes = "0.4"
sha-1 = "0.8"
language-tags = "0.2.2"
unicase = "2.5.1"
percent-encoding = "2.1"
double-checked-cell = "2.0"
atty = "0.2"
rand = "0.7"
multimap = { version = "0.8", features = ["serde"] }
tokio = { version = "0.2", features = ["full"] }

[build-dependencies]
yansi = "0.5"
version_check = "0.1.3"
