[package]
name = "salvo"
version = "0.2.0"
authors = ["Chrislearn Young <chrislearn@hotmail.com>"]
edition = "2018"
description = """
my web framework.
"""
homepage = "https://github.com/kenorld/salvo"
repository = "https://github.com/kenorld/salvo"
readme = "../README.md"
keywords = ["salvo", "web", "framework", "server"]
license = "MIT/Apache-2.0"
categories = ["web-programming::http-server"]

[package.metadata.docs.rs]
all-features = true

[dependencies]
salvo_core = { path = "../core", version = "0.2.0", default-features = false }
salvo_extra = { path = "../extra", version = "0.2.0", default-features = false }
salvo_macro = {path = "../macro", version="0.2.0"}
async-trait = "0.1.22"

[features]
default = ["macro"]
extra = []
macro = []