[package]
name = "example-acme-http01"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
salvo = { path = "../../salvo", features = ["acme"] }
tokio = "1"
tracing-subscriber = "0.3"
tracing = "0.1"
