[package]
edition = "2021"
name = "mysql-rbatis"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["macros"] }
serde = { version = "1", features = ["derive"] }
rbs = "0.1"
log = "0.4"
fast_log = "1.3"
tracing = "0.1"
tracing-subscriber = "0.3"
rbatis = { version = "4.0" }
salvo = { path = "../../salvo" }
rbdc = { version = "0.1" }
rbdc-mysql = { version = "0.1" }
