[package]
name = "file_list"
version = "0.0.0"
workspace = "../../"
edition = "2018"
publish = false

[dependencies]
hyper = "0.13.8"
tracing = "0.1"
tracing-subscriber = "0.2"
salvo_core = { path = "../../core" }
salvo_extra = { path = "../../extra" }
tokio = { version = "0.3.0", features = ["full"] }
