[package]
name = "file_list"
version = "0.0.0"
workspace = "../../"
edition = "2018"
publish = false

[dependencies]
hyper = "0.13.8"
slog = { version = "2.5.2", features = ["max_level_trace", "release_max_level_warn"] }
salvo_core = { path = "../../core" }
salvo_extra = { path = "../../extra" }
tokio = { version = "0.3.0", features = ["full"] }
