[package]
name = "basic_auth"
version = "0.0.0"
workspace = "../../"
edition = "2018"
publish = false

[dependencies]
hyper = {git="https://github.com/hyperium/hyper.git"}
tracing = "0.1"
tracing-subscriber = "0.2"
salvo = { path = "../../salvo" }
salvo_extra = { path = "../../extra" }
tokio = { version = "0.3.0", features = ["full"] }
