[package]
name = "basic_auth"
version = "0.0.0"
workspace = "../../"
edition = "2018"
publish = false

[dependencies]
hyper = "0.14.1"
tracing = "0.1"
tracing-subscriber = "0.2"
salvo = { path = "../../salvo" }
salvo_extra = { path = "../../extra" }
tokio = { version = "1.0", features = ["full"] }
