[package]
name = "example-work-with-tower"
version.workspace = true
edition.workspace = true
publish.workspace = true


[dependencies]
hyper = { workspace = true, features = ["server"] }
salvo = { workspace = true }
tokio = { version = "1", features = ["macros"] }
tower = { version = "0.4", features = ["limit"] }
tracing = "0.1"
tracing-subscriber = "0.3"
