[package]
name = "example-work-with-tower"
version = "0.1.0"
edition = "2021"
publish = false


[dependencies]
salvo = { path = "../../salvo" }
tokio = "1"
tracing-subscriber = "0.3"
tracing = "0.1"
tower = { version = "0.4", features = ["limit"] }
hyper = { version = "0.14", features = ["server"] }
