[package]
name = "example-parse-data"
version = "0.1.0"
edition = "2021"
publish = false


[dependencies]
enumflags2 = "0.7.5"
salvo = { path = "../../salvo" }
serde = { version = "1", features = ["derive"] }
tokio = "1"
tracing = "0.1"
tracing-subscriber = "0.3"
