[package]
name = "example-cors"
version = "0.1.0"
edition = "2021"
publish = false


[dependencies]
salvo = { path = "../../salvo", features = ["cors"] }
tokio = "1"
tracing-subscriber = "0.3"
tracing = "0.1"