[package]
name = "example-todos-utoipa"
version.workspace = true
edition.workspace = true
publish.workspace = true


[dependencies]
once_cell = "1"
salvo = { workspace = true, features = ["affix", "size-limiter"] }
serde = { version = "1.0.118", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["macros"] }
tracing = "0.1"
tracing-subscriber = "0.3"
utoipa = "2.4.2"
utoipa-swagger-ui = "3.0.1"
