[package]
name = "novel-macros"
version = "0.1.1"
authors = ["Chrislearn Young <chrislearn@hotmail.com>"]
edition = "2018"
description = "novel proc macros"
homepage = "https://github.com/kenorld/novel"
repository = "https://github.com/kenorld/novel/macros"
readme = "../README.md"
keywords = ["novel", "web", "framework", "server"]
license = "MIT/Apache-2.0"
categories = ["web-programming::http-server"]

[lib]
name = "novel_macros"
path = "src/lib.rs"
proc-macro = true

[dependencies]
quote = "^1"
syn = { version = "^1", features = ["full", "parsing"] }
proc-macro2 = "^1"

[dev-dependencies]
# novel = { version = "0.5", path="../core"}
# futures = { version = "0.3.1" }
