[package]
name = "salvo_macros"
version = "0.1.0"
authors = ["Chrislearn Young <chrislearn@hotmail.com>"]
edition = "2018"
description = "salvo proc macros"
homepage = "https://github.com/kenorld/salvo"
repository = "https://github.com/kenorld/salvo/macros"
readme = "../README.md"
keywords = ["salvo", "web", "framework", "server"]
license = "MIT/Apache-2.0"
categories = ["web-programming::http-server"]

[lib]
name = "salvo_macros"
path = "src/lib.rs"
proc-macro = true

[dependencies]
quote = "^1"
syn = { version = "^1", features = ["full", "parsing"] }
proc-macro2 = "^1"

[dev-dependencies]
# salvo = { version = "0.5", path="../core"}
# futures = { version = "0.3.1" }
