[package]
name = "example-with-listenfd"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
hyper = { version = "0.14.20", features = ["server"] }
listenfd = "1.0.0"
salvo = { workspace = true }
tokio = { version = "1", features = ["macros"] }
tracing = "0.1"
tracing-subscriber = "0.3"
