[package]
name = "example-rustls-reload"
version = "0.1.0"
edition = "2021"
publish = false


[dependencies]
async-stream = "0.3"
salvo = { path = "../../salvo", features = ["rustls"] }
tokio = "1"
tracing = "0.1"
tracing-subscriber = "0.3"
