[package]
name = "salvo_core"
version.workspace = true
authors = ["Chrislearn Young <chrislearn@hotmail.com>", "driftluo <driftluo@foxmail.com>"]
edition.workspace = true
description.workspace = true
homepage.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
license.workspace = true
categories.workspace = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = ["cookie", "test"]
full = ["rustls", "anyhow"]
cookie = ["dep:cookie"]
rustls = ["dep:tokio-rustls", "dep:rustls-pemfile", "dep:pin-project"]
native-tls = ["dep:tokio-native-tls", "dep:pin-project"]
openssl = ["dep:openssl", "dep:pin-project", "dep:tokio-openssl"]
unix = []
test = ["dep:async-compression", "dep:base64", "dep:encoding_rs", "dep:serde_urlencoded", "dep:url", "tokio/macros"]
acme = ["dep:base64", "hyper/client", "dep:hyper-rustls", "dep:rcgen", "dep:ring", "dep:x509-parser", "dep:tokio-rustls", "dep:rustls-pemfile"]

[dependencies]
cruet.workspace = true
anyhow = { workspace = true, optional = true }
async-compression = { version = "0.3", features = ["brotli", "deflate", "gzip", "tokio"], optional = true }
async-trait.workspace = true
base64 = { workspace = true, optional = true }
bytes = "1"
cookie = { workspace = true, features = ["percent-encode"], optional = true }
encoding_rs = { version = "0.8", optional = true }
enumflags2.workspace = true
fastrand.workspace = true
form_urlencoded = "1"
futures-util = { workspace = true, default-features = false, features = ["io"] }
headers.workspace = true
http.workspace = true
hyper = { workspace = true, features = ["stream", "server", "http1", "http2", "tcp", "client"] }
hyper-rustls = { version = "0.23", optional = true }
mime.workspace = true
mime_guess.workspace = true
multer = "2"
multimap = { workspace = true, features = ["serde"] }
once_cell.workspace = true
parking_lot.workspace = true
percent-encoding.workspace = true
pin-project = { workspace = true, optional = true }
rcgen = { version = "0.9", optional = true }
regex.workspace = true
ring = { version = "0.16", optional = true }
rustls-pemfile = { version = "1.0", optional = true }
salvo_macros = { workspace = true, path = "../macros" }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["raw_value"] }
serde_urlencoded = { workspace = true, optional = true }
tempfile = "3"
textnonce = "1"
thiserror.workspace = true
openssl = { version = "0.10", optional = true }
tokio = { workspace = true, features = ["fs", "rt-multi-thread"] }
tokio-native-tls = { version = "0.3", optional = true }
tokio-rustls = { version = "0.23", optional = true }
tokio-openssl = { version = "0.6", optional = true }
tokio-stream = { workspace = true, default-features = false }
tracing.workspace = true
url = { workspace = true, optional = true }
x509-parser = { version = "0.14", optional = true }

[dev-dependencies]
reqwest = { workspace = true, features = ["json"] }
