[package]
name = "example-ws"
version.workspace = true
edition.workspace = true
publish.workspace = true


[dependencies]
futures-util = { version = "0.3", default-features = false }
salvo = { workspace = true, features = ["ws"] }
tokio = { version = "1", features = ["macros"] }
tracing = "0.1"
tracing-subscriber = "0.3"
serde = "1"
serde_json = "1"
