[package]
name = "example-sse-chat"
version = "0.1.0"
edition = "2021"
publish = false


[dependencies]
salvo = { path = "../../salvo" }
tokio = "1"
tracing-subscriber = "0.3"
tracing = "0.1"
once_cell = "1"
tokio-stream = { version = "0.1", features = ["net"] }
futures-util = { version = "0.3", default-features = false }